version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hungry-panda-api-gateway
    ports:
      - "8089:8089"
    env_file:
      - env.txt
    environment:
      SPRING_APPLICATION_NAME: hungry-panda-api-gateway
      SERVER_PORT: 8089
      
      # Auth0 config (optional if you want to override properties)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://dev-z4q44sumxx3m76z8.eu.auth0.com/
      
      # If you want to pass audience via env (optional, since handled in Java)
      AUTH0_AUDIENCE: https://hungry-panda-api-gateway/
      
    networks:
      - panda-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-net:
    external: true
